sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cristianchira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cristianchira/docker-react npm run test
